{{- if .Values.autoscaling.metrics }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "template.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "template.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "template.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- range $metric := .Values.autoscaling.metrics }}
    - type: Resource
      resource:
        name: {{ $metric.type }}
        targetAverageUtilization: {{ $metric.average_percent }}
    {{- end }}
{{- end }}
